name: Play

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: dixit-docker
  GCE_INSTANCE_ZONE: us-east1-b
 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
        run: |-
         echo `ip addr show docker0 | grep -Po 'inet \K[\d.]+'`
